// web/wasm/matmul.c -> web/js/matmul_wasm.js: the SIMD kernel as base64 in a JS module, which
// the page, its MCTS workers and the Node checks all load without a fetch.
//
// Only clang is needed, not a linker: `clang -c` writes a relocatable WebAssembly object whose
// one import is the memory (env.__linear_memory) and whose functions have no export section,
// since exports are the linker's job. This adds that section (exporting every defined function
// by its name in the object's symbol table) and keeps the rest; the object's custom sections
// (linking, relocations) are inert at run time. Rerun after editing matmul.c and commit both.
//   node showdown/build_wasm.js
'use strict';
const fs = require('fs');
const path = require('path');
const { execFileSync } = require('child_process');

const SRC = path.resolve(__dirname, '../web/wasm/matmul.c');
const OUT = path.resolve(__dirname, '../web/js/matmul_wasm.js');
const OBJ = path.join(require('os').tmpdir(), `matmul-${process.pid}.o`);
execFileSync('clang', ['--target=wasm32', '-O3', '-msimd128', '-c', '-o', OBJ, SRC], { stdio: 'inherit' });
const bytes = fs.readFileSync(OBJ);
fs.unlinkSync(OBJ);

// LEB128 and the section list.
const uleb = (n) => { const out = []; do { let b = n & 0x7f; n >>>= 7; if (n) b |= 0x80; out.push(b); } while (n); return out; };
function readUleb(buf, at) { let n = 0, shift = 0, b; do { b = buf[at++]; n |= (b & 0x7f) << shift; shift += 7; } while (b & 0x80); return [n >>> 0, at]; }
const sections = [];
for (let at = 8; at < bytes.length;) {
  const id = bytes[at];
  const [size, body] = readUleb(bytes, at + 1);
  sections.push({ id, start: at, body, end: body + size });
  at = body + size;
}
// The defined functions' names, from the `linking` custom section's symbol table.
const linking = sections.find((s) => s.id === 0 && bytes.subarray(s.body + 1, s.body + 1 + bytes[s.body]).toString() === 'linking');
const names = new Map();
{
  let at = linking.body + 1 + bytes[linking.body];
  [, at] = readUleb(bytes, at);  // version
  while (at < linking.end) {
    const kind = bytes[at];
    let size; [size, at] = readUleb(bytes, at + 1);
    const end = at + size;
    if (kind === 8) {  // WASM_SYMBOL_TABLE
      let count; [count, at] = readUleb(bytes, at);
      for (let s = 0; s < count; s++) {
        const type = bytes[at++];
        let flags; [flags, at] = readUleb(bytes, at);
        if (type === 0) {  // a function
          let index; [index, at] = readUleb(bytes, at);
          if (!(flags & 0x10)) {  // not undefined: it has a name here
            let len; [len, at] = readUleb(bytes, at);
            const name = bytes.subarray(at, at + len).toString();
            at += len;
            if (!(flags & 0x2)) names.set(name, index);  // not local (static): exported
          }
        } else {
          throw new Error(`build_wasm: a symbol of kind ${type}; matmul.c must stay a leaf with no data`);
        }
      }
    }
    at = end;
  }
}
const exportBody = [...uleb(names.size)];
for (const [name, index] of names) exportBody.push(...uleb(name.length), ...Buffer.from(name), 0x00, ...uleb(index));
const exportSection = Buffer.from([7, ...uleb(exportBody.length), ...exportBody]);
// Exports go after the function section (3), memory (5) and globals (6), before the code (10).
const before = sections.findIndex((s) => s.id !== 0 && s.id > 7);
const at = sections[before].start;
const wasm = Buffer.concat([bytes.subarray(0, at), exportSection, bytes.subarray(at)]);
if (!WebAssembly.validate(wasm)) throw new Error('build_wasm: the module does not validate');
const exported = WebAssembly.Module.exports(new WebAssembly.Module(wasm)).map((e) => e.name);
fs.writeFileSync(OUT, `// Generated by showdown/build_wasm.js from web/wasm/matmul.c: do not edit. Exports ${exported.join(', ')}.\n`
  + `export const MATMUL_WASM = '${wasm.toString('base64')}';\n`);
console.log(`${OUT}: ${wasm.length} bytes, exports ${exported.join(', ')}`);
