"""Tables shared by the three gate implementations.

Values come from artifacts/dex_raw.json (Showdown 0.11.11, gen3 mod) and are
inlined here so the benchmark reads no files at run time. The C header for the
raw-CUDA version is generated from these same literals, so all three
implementations cannot drift apart.
"""

TYPES = ('Normal', 'Fighting', 'Flying', 'Poison', 'Ground', 'Rock', 'Bug', 'Ghost', 'Steel',
         'Fire', 'Water', 'Grass', 'Electric', 'Psychic', 'Ice', 'Dragon', 'Dark', '???')
NTYPES = len(TYPES)
IMMUNE = -8  # sentinel; any negative sum below -6 means zero damage

# CHART[attacking][defending]: +1 double, 0 neutral, -1 half, IMMUNE no effect.
CHART = (
    (0, 0, 0, 0, 0, -1, 0, IMMUNE, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0),
    (1, 0, -1, -1, 0, 1, -1, IMMUNE, 1, 0, 0, 0, 0, -1, 1, 0, 1, 0),
    (0, 1, 0, 0, 0, -1, 1, 0, -1, 0, 0, 1, -1, 0, 0, 0, 0, 0),
    (0, 0, 0, -1, -1, -1, 0, -1, IMMUNE, 0, 0, 1, 0, 0, 0, 0, 0, 0),
    (0, 0, IMMUNE, 1, 0, 1, -1, 0, 1, 1, 0, -1, 1, 0, 0, 0, 0, 0),
    (0, -1, 1, 0, -1, 0, 1, 0, -1, 1, 0, 0, 0, 0, 1, 0, 0, 0),
    (0, -1, -1, -1, 0, 0, 0, -1, -1, -1, 0, 1, 0, 1, 0, 0, 1, 0),
    (IMMUNE, 0, 0, 0, 0, 0, 0, 1, -1, 0, 0, 0, 0, 1, 0, 0, -1, 0),
    (0, 0, 0, 0, 0, 1, 0, 0, -1, -1, -1, 0, -1, 0, 1, 0, 0, 0),
    (0, 0, 0, 0, 0, -1, 1, 0, 1, -1, -1, 1, 0, 0, 1, -1, 0, 0),
    (0, 0, 0, 0, 1, 1, 0, 0, 0, 1, -1, -1, 0, 0, 0, -1, 0, 0),
    (0, 0, -1, -1, 1, 1, -1, 0, -1, -1, 1, -1, 0, 0, 0, -1, 0, 0),
    (0, 0, 1, 0, IMMUNE, 0, 0, 0, 0, 0, 1, -1, -1, 0, 0, -1, 0, 0),
    (0, 1, 0, 1, 0, 0, 0, 0, -1, 0, 0, 0, 0, -1, 0, 0, IMMUNE, 0),
    (0, 0, 1, 0, 1, 0, 0, 0, -1, -1, -1, 1, 0, 0, -1, 1, 0, 0),
    (0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 0, 0, 0, 0, 0, 1, 0, 0),
    (0, -1, 0, 0, 0, 0, 0, 1, -1, 0, 0, 0, 0, 1, 0, 0, -1, 0),
    (0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
)

PHYSICAL, SPECIAL, STATUS_CAT = 0, 1, 2
PAR, PSN, TOX, BRN, FRZ = 1, 2, 3, 4, 5
NEVER_MISS = 255

# Families: the dispatch the benchmark is actually measuring.
F_DAMAGE, F_SEC_STATUS, F_SEC_DROP, F_STATUS, F_BOOST, F_MULTI, F_RECOIL, F_DRAIN, F_FIXED, F_FLINCH = range(10)
NFAMILIES = 10

# name, type, category, power, accuracy, family, p0, p1
MOVES = (
    ('earthquake', 4, PHYSICAL, 100, 100, F_DAMAGE, 0, 0),
    ('rockslide', 5, PHYSICAL, 75, 90, F_FLINCH, 30, 0),
    ('hydropump', 10, SPECIAL, 120, 80, F_DAMAGE, 0, 0),
    ('surf', 10, SPECIAL, 95, 100, F_DAMAGE, 0, 0),
    ('icebeam', 14, SPECIAL, 95, 100, F_SEC_STATUS, 10, FRZ),
    ('thunderbolt', 12, SPECIAL, 95, 100, F_SEC_STATUS, 10, PAR),
    ('bodyslam', 0, PHYSICAL, 85, 100, F_SEC_STATUS, 30, PAR),
    ('doubleedge', 0, PHYSICAL, 120, 100, F_RECOIL, 1, 3),
    ('gigadrain', 11, SPECIAL, 60, 100, F_DRAIN, 1, 2),
    ('hiddenpowerfire', 9, SPECIAL, 70, 100, F_DAMAGE, 0, 0),
    ('shadowball', 7, PHYSICAL, 80, 100, F_SEC_DROP, 20, 3),
    ('sludgebomb', 3, PHYSICAL, 90, 100, F_SEC_STATUS, 30, PSN),
    ('fireblast', 9, SPECIAL, 120, 85, F_SEC_STATUS, 10, BRN),
    ('crunch', 16, SPECIAL, 80, 100, F_SEC_DROP, 20, 3),
    ('bonemerang', 4, PHYSICAL, 50, 90, F_MULTI, 2, 2),
    ('brickbreak', 1, PHYSICAL, 75, 100, F_DAMAGE, 0, 0),
    ('swordsdance', 0, STATUS_CAT, 0, NEVER_MISS, F_BOOST, 0b00001, 2),
    ('calmmind', 13, STATUS_CAT, 0, NEVER_MISS, F_BOOST, 0b01100, 1),
    ('toxic', 3, STATUS_CAT, 0, 85, F_STATUS, TOX, 0),
    ('seismictoss', 1, PHYSICAL, 0, 100, F_FIXED, 0, 0),
)
NMOVES = len(MOVES)
MOVE_COLS = tuple(tuple(m[1:]) for m in MOVES)  # type, cat, power, acc, family, p0, p1


def c_header() -> str:
    """The same tables as a C header, so gate.cu cannot drift from the Python side."""
    chart = ',\n'.join('    {' + ', '.join(f'{v:3d}' for v in row) + '}' for row in CHART)
    moves = '\n'.join('    {' + ', '.join(f'{v:3d}' for v in row) + f'}},  // {MOVES[i][0]}'
                      for i, row in enumerate(MOVE_COLS))
    return (f'// Generated by bench/microbench/tables.py. Do not edit.\n'
            f'#define NTYPES {NTYPES}\n#define NMOVES {NMOVES}\n#define IMMUNE ({IMMUNE})\n'
            f'#define NEVER_MISS {NEVER_MISS}\n\n'
            f'__device__ __constant__ signed char CHART[{NTYPES}][{NTYPES}] = {{\n{chart}\n}};\n\n'
            f'__device__ __constant__ int MOVES[{NMOVES}][7] = {{\n{moves}\n}};\n')
