"""Generated by advsim/build/codegen.py. Do not edit."""

import warp as wp

from advsim.engine import hash as hash_
from advsim.engine._generated.state import State

N_WORDS = 495


@wp.func
def full_hash(s: State, b: int) -> wp.uint64:
    """Every field but `err`: replay diffing against Showdown."""
    h = wp.uint64(0)
    h = h ^ hash_.word(0, wp.uint32(s.weather[b]))
    h = h ^ hash_.word(1, wp.uint32(s.weather_turns[b]))
    h = h ^ hash_.word(2, wp.uint32(s.turn[b]))
    h = h ^ hash_.word(3, wp.uint32(s.result[b]))
    h = h ^ hash_.word(4, wp.uint32(s.last_used[b]))
    h = h ^ hash_.word(5, wp.uint32(s.rng_key[b]))
    h = h ^ hash_.word(6, wp.uint32(s.rng_ctr[b]))
    h = h ^ hash_.word(7, wp.uint32(s.rng_mode[b]))
    h = h ^ hash_.word(9, wp.uint32(s.phase[b]))
    h = h ^ hash_.word(10, wp.uint32(s.turn_first[b]))
    for p in range(2):
        h = h ^ hash_.word(p + 11, wp.uint32(s.pending_act[b, p]))
    for p in range(2):
        h = h ^ hash_.word(p + 13, wp.uint32(s.active[b, p]))
    for p in range(2):
        h = h ^ hash_.word(p + 15, wp.uint32(s.request[b, p]))
    for p in range(2):
        h = h ^ hash_.word(p + 17, wp.uint32(s.spikes[b, p]))
    for p in range(2):
        h = h ^ hash_.word(p + 19, wp.uint32(s.wish_turns[b, p]))
    for p in range(2):
        h = h ^ hash_.word(p + 21, wp.uint32(s.alive_mask[b, p]))
    for p in range(2):
        h = h ^ hash_.word(p + 23, wp.uint32(s.knocked_mask[b, p]))
    for p in range(2):
        h = h ^ hash_.word(p + 25, wp.uint32(s.truant_mask[b, p]))
    for p in range(2):
        h = h ^ hash_.word(p + 27, wp.uint32(s.boosts[b, p]))
    for p in range(2):
        h = h ^ hash_.word(p + 29, wp.uint32(s.vflags[b, p]))
    for p in range(2):
        h = h ^ hash_.word(p + 31, wp.uint32(s.sub_hp[b, p]))
    for p in range(2):
        h = h ^ hash_.word(p + 33, wp.uint32(s.confusion_turns[b, p]))
    for p in range(2):
        h = h ^ hash_.word(p + 35, wp.uint32(s.encore_turns[b, p]))
    for p in range(2):
        h = h ^ hash_.word(p + 37, wp.uint32(s.encore_move[b, p]))
    for p in range(2):
        h = h ^ hash_.word(p + 39, wp.uint32(s.choice_move[b, p]))
    for p in range(2):
        h = h ^ hash_.word(p + 41, wp.uint32(s.trap_turns[b, p]))
    for p in range(2):
        h = h ^ hash_.word(p + 43, wp.uint32(s.trap_source[b, p]))
    for p in range(2):
        h = h ^ hash_.word(p + 45, wp.uint32(s.perish_count[b, p]))
    for p in range(2):
        h = h ^ hash_.word(p + 47, wp.uint32(s.yawn_turns[b, p]))
    for p in range(2):
        h = h ^ hash_.word(p + 49, wp.uint32(s.stall_ctr[b, p]))
    for p in range(2):
        h = h ^ hash_.word(p + 51, wp.uint32(s.twoturn_move[b, p]))
    for p in range(2):
        h = h ^ hash_.word(p + 53, wp.uint32(s.last_move[b, p]))
    for p in range(2):
        h = h ^ hash_.word(p + 55, wp.uint32(s.dmg_taken[b, p]))
    for p in range(2):
        h = h ^ hash_.word(p + 57, wp.uint32(s.dmg_cat[b, p]))
    for p in range(2):
        for m in range(2):
            h = h ^ hash_.word(p * 2 + m + 59, wp.uint32(s.types[b, p, m]))
    for p in range(2):
        h = h ^ hash_.word(p + 63, wp.uint32(s.turn_flags[b, p]))
    for p in range(2):
        h = h ^ hash_.word(p + 65, wp.uint32(s.moved_at[b, p]))
    for p in range(2):
        h = h ^ hash_.word(p + 67, wp.uint32(s.moved_prio[b, p]))
    for p in range(2):
        for m in range(5):
            h = h ^ hash_.word(p * 5 + m + 69, wp.uint32(s.xf_stats[b, p, m]))
    for p in range(2):
        for m in range(4):
            h = h ^ hash_.word(p * 4 + m + 79, wp.uint32(s.xf_moves[b, p, m]))
    for p in range(2):
        for m in range(4):
            h = h ^ hash_.word(p * 4 + m + 87, wp.uint32(s.xf_pp[b, p, m]))
    for p in range(2):
        for m in range(4):
            h = h ^ hash_.word(p * 4 + m + 95, wp.uint32(s.xf_max_pp[b, p, m]))
    for p in range(2):
        h = h ^ hash_.word(p + 103, wp.uint32(s.xf_ability[b, p]))
    for p in range(2):
        h = h ^ hash_.word(p + 105, wp.uint32(s.xf_species[b, p]))
    for p in range(2):
        h = h ^ hash_.word(p + 107, wp.uint32(s.xf_hp_type[b, p]))
    for p in range(2):
        h = h ^ hash_.word(p + 109, wp.uint32(s.base_ability[b, p]))
    for p in range(2):
        for m in range(6):
            h = h ^ hash_.word(p * 6 + m + 111, wp.uint32(s.cached_spe[b, p, m]))
    for p in range(2):
        for m in range(6):
            h = h ^ hash_.word(p * 6 + m + 123, wp.uint32(s.hp[b, p, m]))
    for p in range(2):
        for m in range(6):
            h = h ^ hash_.word(p * 6 + m + 135, wp.uint32(s.status[b, p, m]))
    for p in range(2):
        for m in range(6):
            h = h ^ hash_.word(p * 6 + m + 147, wp.uint32(s.status_ctr[b, p, m]))
    for p in range(2):
        for m in range(6):
            h = h ^ hash_.word(p * 6 + m + 159, wp.uint32(s.sleep_skipped[b, p, m]))
    for p in range(2):
        for m in range(6):
            h = h ^ hash_.word(p * 6 + m + 171, wp.uint32(s.slept_by_foe[b, p, m]))
    for p in range(2):
        for m in range(6):
            h = h ^ hash_.word(p * 6 + m + 183, wp.uint32(s.species[b, p, m]))
    for p in range(2):
        for m in range(6):
            h = h ^ hash_.word(p * 6 + m + 195, wp.uint32(s.level[b, p, m]))
    for p in range(2):
        for m in range(6):
            h = h ^ hash_.word(p * 6 + m + 207, wp.uint32(s.gender[b, p, m]))
    for p in range(2):
        for m in range(6):
            h = h ^ hash_.word(p * 6 + m + 219, wp.uint32(s.ability[b, p, m]))
    for p in range(2):
        for m in range(6):
            h = h ^ hash_.word(p * 6 + m + 231, wp.uint32(s.item[b, p, m]))
    for p in range(2):
        for m in range(6):
            h = h ^ hash_.word(p * 6 + m + 243, wp.uint32(s.hp_type[b, p, m]))
    for p in range(2):
        for m in range(6):
            for c in range(5):
                h = h ^ hash_.word(p * 30 + m * 5 + c + 255, wp.uint32(s.stats[b, p, m, c]))
    for p in range(2):
        for m in range(6):
            h = h ^ hash_.word(p * 6 + m + 315, wp.uint32(s.maxhp[b, p, m]))
    for p in range(2):
        for m in range(6):
            for c in range(4):
                h = h ^ hash_.word(p * 24 + m * 4 + c + 327, wp.uint32(s.moves[b, p, m, c]))
    for p in range(2):
        for m in range(6):
            for c in range(4):
                h = h ^ hash_.word(p * 24 + m * 4 + c + 375, wp.uint32(s.pp[b, p, m, c]))
    for p in range(2):
        for m in range(6):
            for c in range(4):
                h = h ^ hash_.word(p * 24 + m * 4 + c + 423, wp.uint32(s.max_pp[b, p, m, c]))
    for p in range(2):
        for m in range(6):
            h = h ^ hash_.word(p * 6 + m + 471, wp.uint32(s.party_pos[b, p, m]))
    for p in range(2):
        for m in range(6):
            h = h ^ hash_.word(p * 6 + m + 483, wp.uint32(s.revealed[b, p, m]))
    return h


@wp.func
def position_hash(s: State, b: int) -> wp.uint64:
    """Game-relevant fields only: transpositions, perft, world dedup."""
    h = wp.uint64(0)
    h = h ^ hash_.word(0, wp.uint32(s.weather[b]))
    h = h ^ hash_.word(1, wp.uint32(s.weather_turns[b]))
    h = h ^ hash_.word(3, wp.uint32(s.result[b]))
    h = h ^ hash_.word(4, wp.uint32(s.last_used[b]))
    h = h ^ hash_.word(9, wp.uint32(s.phase[b]))
    h = h ^ hash_.word(10, wp.uint32(s.turn_first[b]))
    for p in range(2):
        h = h ^ hash_.word(p + 11, wp.uint32(s.pending_act[b, p]))
    for p in range(2):
        h = h ^ hash_.word(p + 13, wp.uint32(s.active[b, p]))
    for p in range(2):
        h = h ^ hash_.word(p + 15, wp.uint32(s.request[b, p]))
    for p in range(2):
        h = h ^ hash_.word(p + 17, wp.uint32(s.spikes[b, p]))
    for p in range(2):
        h = h ^ hash_.word(p + 19, wp.uint32(s.wish_turns[b, p]))
    for p in range(2):
        h = h ^ hash_.word(p + 21, wp.uint32(s.alive_mask[b, p]))
    for p in range(2):
        h = h ^ hash_.word(p + 23, wp.uint32(s.knocked_mask[b, p]))
    for p in range(2):
        h = h ^ hash_.word(p + 25, wp.uint32(s.truant_mask[b, p]))
    for p in range(2):
        h = h ^ hash_.word(p + 27, wp.uint32(s.boosts[b, p]))
    for p in range(2):
        h = h ^ hash_.word(p + 29, wp.uint32(s.vflags[b, p]))
    for p in range(2):
        h = h ^ hash_.word(p + 31, wp.uint32(s.sub_hp[b, p]))
    for p in range(2):
        h = h ^ hash_.word(p + 33, wp.uint32(s.confusion_turns[b, p]))
    for p in range(2):
        h = h ^ hash_.word(p + 35, wp.uint32(s.encore_turns[b, p]))
    for p in range(2):
        h = h ^ hash_.word(p + 37, wp.uint32(s.encore_move[b, p]))
    for p in range(2):
        h = h ^ hash_.word(p + 39, wp.uint32(s.choice_move[b, p]))
    for p in range(2):
        h = h ^ hash_.word(p + 41, wp.uint32(s.trap_turns[b, p]))
    for p in range(2):
        h = h ^ hash_.word(p + 43, wp.uint32(s.trap_source[b, p]))
    for p in range(2):
        h = h ^ hash_.word(p + 45, wp.uint32(s.perish_count[b, p]))
    for p in range(2):
        h = h ^ hash_.word(p + 47, wp.uint32(s.yawn_turns[b, p]))
    for p in range(2):
        h = h ^ hash_.word(p + 49, wp.uint32(s.stall_ctr[b, p]))
    for p in range(2):
        h = h ^ hash_.word(p + 51, wp.uint32(s.twoturn_move[b, p]))
    for p in range(2):
        h = h ^ hash_.word(p + 53, wp.uint32(s.last_move[b, p]))
    for p in range(2):
        h = h ^ hash_.word(p + 55, wp.uint32(s.dmg_taken[b, p]))
    for p in range(2):
        h = h ^ hash_.word(p + 57, wp.uint32(s.dmg_cat[b, p]))
    for p in range(2):
        for m in range(2):
            h = h ^ hash_.word(p * 2 + m + 59, wp.uint32(s.types[b, p, m]))
    for p in range(2):
        h = h ^ hash_.word(p + 63, wp.uint32(s.turn_flags[b, p]))
    for p in range(2):
        h = h ^ hash_.word(p + 65, wp.uint32(s.moved_at[b, p]))
    for p in range(2):
        h = h ^ hash_.word(p + 67, wp.uint32(s.moved_prio[b, p]))
    for p in range(2):
        for m in range(5):
            h = h ^ hash_.word(p * 5 + m + 69, wp.uint32(s.xf_stats[b, p, m]))
    for p in range(2):
        for m in range(4):
            h = h ^ hash_.word(p * 4 + m + 79, wp.uint32(s.xf_moves[b, p, m]))
    for p in range(2):
        for m in range(4):
            h = h ^ hash_.word(p * 4 + m + 87, wp.uint32(s.xf_pp[b, p, m]))
    for p in range(2):
        for m in range(4):
            h = h ^ hash_.word(p * 4 + m + 95, wp.uint32(s.xf_max_pp[b, p, m]))
    for p in range(2):
        h = h ^ hash_.word(p + 103, wp.uint32(s.xf_ability[b, p]))
    for p in range(2):
        h = h ^ hash_.word(p + 105, wp.uint32(s.xf_species[b, p]))
    for p in range(2):
        h = h ^ hash_.word(p + 107, wp.uint32(s.xf_hp_type[b, p]))
    for p in range(2):
        h = h ^ hash_.word(p + 109, wp.uint32(s.base_ability[b, p]))
    for p in range(2):
        for m in range(6):
            h = h ^ hash_.word(p * 6 + m + 111, wp.uint32(s.cached_spe[b, p, m]))
    for p in range(2):
        for m in range(6):
            h = h ^ hash_.word(p * 6 + m + 123, wp.uint32(s.hp[b, p, m]))
    for p in range(2):
        for m in range(6):
            h = h ^ hash_.word(p * 6 + m + 135, wp.uint32(s.status[b, p, m]))
    for p in range(2):
        for m in range(6):
            h = h ^ hash_.word(p * 6 + m + 147, wp.uint32(s.status_ctr[b, p, m]))
    for p in range(2):
        for m in range(6):
            h = h ^ hash_.word(p * 6 + m + 159, wp.uint32(s.sleep_skipped[b, p, m]))
    for p in range(2):
        for m in range(6):
            h = h ^ hash_.word(p * 6 + m + 171, wp.uint32(s.slept_by_foe[b, p, m]))
    for p in range(2):
        for m in range(6):
            h = h ^ hash_.word(p * 6 + m + 183, wp.uint32(s.species[b, p, m]))
    for p in range(2):
        for m in range(6):
            h = h ^ hash_.word(p * 6 + m + 195, wp.uint32(s.level[b, p, m]))
    for p in range(2):
        for m in range(6):
            h = h ^ hash_.word(p * 6 + m + 207, wp.uint32(s.gender[b, p, m]))
    for p in range(2):
        for m in range(6):
            h = h ^ hash_.word(p * 6 + m + 219, wp.uint32(s.ability[b, p, m]))
    for p in range(2):
        for m in range(6):
            h = h ^ hash_.word(p * 6 + m + 231, wp.uint32(s.item[b, p, m]))
    for p in range(2):
        for m in range(6):
            h = h ^ hash_.word(p * 6 + m + 243, wp.uint32(s.hp_type[b, p, m]))
    for p in range(2):
        for m in range(6):
            for c in range(5):
                h = h ^ hash_.word(p * 30 + m * 5 + c + 255, wp.uint32(s.stats[b, p, m, c]))
    for p in range(2):
        for m in range(6):
            h = h ^ hash_.word(p * 6 + m + 315, wp.uint32(s.maxhp[b, p, m]))
    for p in range(2):
        for m in range(6):
            for c in range(4):
                h = h ^ hash_.word(p * 24 + m * 4 + c + 327, wp.uint32(s.moves[b, p, m, c]))
    for p in range(2):
        for m in range(6):
            for c in range(4):
                h = h ^ hash_.word(p * 24 + m * 4 + c + 375, wp.uint32(s.pp[b, p, m, c]))
    for p in range(2):
        for m in range(6):
            for c in range(4):
                h = h ^ hash_.word(p * 24 + m * 4 + c + 423, wp.uint32(s.max_pp[b, p, m, c]))
    for p in range(2):
        for m in range(6):
            h = h ^ hash_.word(p * 6 + m + 471, wp.uint32(s.party_pos[b, p, m]))
    return h
