"""Generated by advsim/build/codegen.py. Do not edit."""

import warp as wp


@wp.struct
class State:
    weather: wp.array(dtype=wp.uint8)  # [B] none, sun, rain, sand
    weather_turns: wp.array(dtype=wp.uint8)  # [B] 0 turns means ability-set and permanent
    turn: wp.array(dtype=wp.uint16)  # [B] excluded from the position hash; Endless Battle Clause ends at 1,000
    result: wp.array(dtype=wp.uint8)  # [B] ongoing, p1, p2, tie
    last_used: wp.array(dtype=wp.uint8)  # [B] Showdown's battle.lastMove: the last move past BeforeMove and PP, Sleep Talk rather than its call; the Emerald chooser reads it
    rng_key: wp.array(dtype=wp.uint32)  # [B]
    rng_ctr: wp.array(dtype=wp.uint32)  # [B] replay mode uses this as a log cursor
    rng_mode: wp.array(dtype=wp.uint8)  # [B] train, paired, replay
    err: wp.array(dtype=wp.uint8)  # [B] bits: illegal action (mask.ERR_ILLEGAL), replay log exhausted (mask.ERR_LOG_EXHAUSTED)
    phase: wp.array(dtype=wp.uint8)  # [B] how far into the turn: a faint pauses it for a replacement
    turn_first: wp.array(dtype=wp.uint8)  # [B] which side won the order roll for the turn in progress
    pending_act: wp.array2d(dtype=wp.uint8)  # [B][2] the actions chosen for the turn in progress
    active: wp.array2d(dtype=wp.uint8)  # [B][2] index into the party
    request: wp.array2d(dtype=wp.uint8)  # [B][2] none, move, forced switch, wait
    spikes: wp.array2d(dtype=wp.uint8)  # [B][2] 0 to 3 layers
    wish_turns: wp.array2d(dtype=wp.uint8)  # [B][2] gen 3 heals half the max HP of whoever is in the slot, so no amount is stored
    alive_mask: wp.array2d(dtype=wp.uint8)  # [B][2] 6 bits
    knocked_mask: wp.array2d(dtype=wp.uint8)  # [B][2] 6 bits: gen 3 Knock Off leaves a Pokemon unable to take an item for the rest of the battle
    truant_mask: wp.array2d(dtype=wp.uint8)  # [B][2] 6 bits: `truantTurn` is a property of the Pokemon, not a volatile, so it survives a switch. Only a traced Truant can see that, since a real one resets it on the way in
    boosts: wp.array2d(dtype=wp.uint32)  # [B][2] 7 signed nibbles: atk, def, spa, spd, spe, acc, eva
    vflags: wp.array2d(dtype=wp.uint32)  # [B][2] one bit per volatile
    sub_hp: wp.array2d(dtype=wp.uint16)  # [B][2]
    confusion_turns: wp.array2d(dtype=wp.uint8)  # [B][2]
    encore_turns: wp.array2d(dtype=wp.uint8)  # [B][2]
    encore_move: wp.array2d(dtype=wp.uint8)  # [B][2]
    choice_move: wp.array2d(dtype=wp.uint8)  # [B][2] the foe knows the lock only once it knows the item
    trap_turns: wp.array2d(dtype=wp.uint8)  # [B][2]
    trap_source: wp.array2d(dtype=wp.uint8)  # [B][2] party slot of the Pokemon holding the trap, plus one; the trap ends when it is no longer the one across the field. The holder is on the other side, so it moves with that side's order
    perish_count: wp.array2d(dtype=wp.uint8)  # [B][2]
    yawn_turns: wp.array2d(dtype=wp.uint8)  # [B][2]
    stall_ctr: wp.array2d(dtype=wp.uint8)  # [B][2] consecutive Protect or Endure
    twoturn_move: wp.array2d(dtype=wp.uint8)  # [B][2] Solar Beam charge
    last_move: wp.array2d(dtype=wp.uint8)  # [B][2] Encore target
    dmg_taken: wp.array2d(dtype=wp.uint16)  # [B][2] Counter and Mirror Coat
    dmg_cat: wp.array2d(dtype=wp.uint8)  # [B][2]
    types: wp.array3d(dtype=wp.uint8)  # [B][2][2] current types: Forecast, Color Change, Transform
    turn_flags: wp.array2d(dtype=wp.uint16)  # [B][2] what this side has already done this turn: switched in, released a charge, queued a beforeTurnMove, and so on
    moved_at: wp.array2d(dtype=wp.uint8)  # [B][2] this turn (or the last, until the next starts): 1 if this side used a move of its own action first, 2 second, 0 not at all; what the protocol shows as its move line
    moved_prio: wp.array2d(dtype=wp.uint8)  # [B][2] that move's priority plus 8
    xf_stats: wp.array3d(dtype=wp.uint16)  # [B][2][5] what a transformed Pokemon was before it copied anything; the live fields carry the copy, the way Showdown mutates the Pokemon itself
    xf_moves: wp.array3d(dtype=wp.uint8)  # [B][2][4]
    xf_pp: wp.array3d(dtype=wp.uint8)  # [B][2][4]
    xf_max_pp: wp.array3d(dtype=wp.uint8)  # [B][2][4] Showdown keeps the PP Ups on the Pokemon and rebuilds a transformed slot's maxpp from them, so a copy needs the original back to revert to
    xf_ability: wp.array2d(dtype=wp.uint8)  # [B][2]
    xf_species: wp.array2d(dtype=wp.uint16)  # [B][2]
    xf_hp_type: wp.array2d(dtype=wp.uint8)  # [B][2]
    base_ability: wp.array2d(dtype=wp.uint8)  # [B][2] what a Trace holder had before it copied, plus one; the copy goes when it leaves
    cached_spe: wp.array3d(dtype=wp.uint16)  # [B][2][6] Showdown's `pokemon.speed`, which every sort reads. setSpecies writes the raw stat and only updateSpeed refreshes it, and only for the actives, so a Pokemon keeps the Speed it last had on the field while it sits on the bench
    hp: wp.array3d(dtype=wp.uint16)  # [B][2][6] absolute; the observation converts to percent
    status: wp.array3d(dtype=wp.uint8)  # [B][2][6]
    status_ctr: wp.array3d(dtype=wp.uint8)  # [B][2][6] sleep turns or toxic stage. Sleep a foe caused lasts a hidden roll; Rest and the toxic stage are counted in the open
    sleep_skipped: wp.array3d(dtype=wp.uint8)  # [B][2][6] gen 3 gives back the turns Sleep Talk spent asleep when the Pokemon switches back in
    slept_by_foe: wp.array3d(dtype=wp.uint8)  # [B][2][6] Sleep Clause Mod; Rest does not count
    species: wp.array3d(dtype=wp.uint16)  # [B][2][6]
    level: wp.array3d(dtype=wp.uint8)  # [B][2][6]
    gender: wp.array3d(dtype=wp.uint8)  # [B][2][6] Cute Charm
    ability: wp.array3d(dtype=wp.uint8)  # [B][2][6]
    item: wp.array3d(dtype=wp.uint8)  # [B][2][6] mutable: Trick, Knock Off
    hp_type: wp.array3d(dtype=wp.uint8)  # [B][2][6]
    stats: wp.array4d(dtype=wp.uint16)  # [B][2][6][5]
    maxhp: wp.array3d(dtype=wp.uint16)  # [B][2][6]
    moves: wp.array4d(dtype=wp.uint8)  # [B][2][6][4]
    pp: wp.array4d(dtype=wp.uint8)  # [B][2][6][4]
    max_pp: wp.array4d(dtype=wp.uint8)  # [B][2][6][4]
    party_pos: wp.array3d(dtype=wp.uint8)  # [B][2][6] where this Pokemon sits in Showdown's own party array, which a drag samples over
    revealed: wp.array3d(dtype=wp.uint16)  # [B][2][6] what the foe has seen: bit 0 the Pokemon, 1-4 its move slots, 5 ability, 6 item; excluded from the position hash, which is about the game and not who knows what


@wp.func
def clear_battle(s: State, b: int):
    s.weather[b] = wp.uint8(0)
    s.weather_turns[b] = wp.uint8(0)
    s.turn[b] = wp.uint16(0)
    s.result[b] = wp.uint8(0)
    s.last_used[b] = wp.uint8(0)
    s.rng_key[b] = wp.uint32(0)
    s.rng_ctr[b] = wp.uint32(0)
    s.rng_mode[b] = wp.uint8(0)
    s.err[b] = wp.uint8(0)
    s.phase[b] = wp.uint8(0)
    s.turn_first[b] = wp.uint8(0)
    for i0 in range(2):
        s.pending_act[b, i0] = wp.uint8(0)
    for i0 in range(2):
        s.active[b, i0] = wp.uint8(0)
    for i0 in range(2):
        s.request[b, i0] = wp.uint8(0)
    for i0 in range(2):
        s.spikes[b, i0] = wp.uint8(0)
    for i0 in range(2):
        s.wish_turns[b, i0] = wp.uint8(0)
    for i0 in range(2):
        s.alive_mask[b, i0] = wp.uint8(0)
    for i0 in range(2):
        s.knocked_mask[b, i0] = wp.uint8(0)
    for i0 in range(2):
        s.truant_mask[b, i0] = wp.uint8(0)
    for i0 in range(2):
        s.boosts[b, i0] = wp.uint32(0)
    for i0 in range(2):
        s.vflags[b, i0] = wp.uint32(0)
    for i0 in range(2):
        s.sub_hp[b, i0] = wp.uint16(0)
    for i0 in range(2):
        s.confusion_turns[b, i0] = wp.uint8(0)
    for i0 in range(2):
        s.encore_turns[b, i0] = wp.uint8(0)
    for i0 in range(2):
        s.encore_move[b, i0] = wp.uint8(0)
    for i0 in range(2):
        s.choice_move[b, i0] = wp.uint8(0)
    for i0 in range(2):
        s.trap_turns[b, i0] = wp.uint8(0)
    for i0 in range(2):
        s.trap_source[b, i0] = wp.uint8(0)
    for i0 in range(2):
        s.perish_count[b, i0] = wp.uint8(0)
    for i0 in range(2):
        s.yawn_turns[b, i0] = wp.uint8(0)
    for i0 in range(2):
        s.stall_ctr[b, i0] = wp.uint8(0)
    for i0 in range(2):
        s.twoturn_move[b, i0] = wp.uint8(0)
    for i0 in range(2):
        s.last_move[b, i0] = wp.uint8(0)
    for i0 in range(2):
        s.dmg_taken[b, i0] = wp.uint16(0)
    for i0 in range(2):
        s.dmg_cat[b, i0] = wp.uint8(0)
    for i0 in range(2):
        for i1 in range(2):
            s.types[b, i0, i1] = wp.uint8(0)
    for i0 in range(2):
        s.turn_flags[b, i0] = wp.uint16(0)
    for i0 in range(2):
        s.moved_at[b, i0] = wp.uint8(0)
    for i0 in range(2):
        s.moved_prio[b, i0] = wp.uint8(0)
    for i0 in range(2):
        for i1 in range(5):
            s.xf_stats[b, i0, i1] = wp.uint16(0)
    for i0 in range(2):
        for i1 in range(4):
            s.xf_moves[b, i0, i1] = wp.uint8(0)
    for i0 in range(2):
        for i1 in range(4):
            s.xf_pp[b, i0, i1] = wp.uint8(0)
    for i0 in range(2):
        for i1 in range(4):
            s.xf_max_pp[b, i0, i1] = wp.uint8(0)
    for i0 in range(2):
        s.xf_ability[b, i0] = wp.uint8(0)
    for i0 in range(2):
        s.xf_species[b, i0] = wp.uint16(0)
    for i0 in range(2):
        s.xf_hp_type[b, i0] = wp.uint8(0)
    for i0 in range(2):
        s.base_ability[b, i0] = wp.uint8(0)
    for i0 in range(2):
        for i1 in range(6):
            s.cached_spe[b, i0, i1] = wp.uint16(0)
    for i0 in range(2):
        for i1 in range(6):
            s.hp[b, i0, i1] = wp.uint16(0)
    for i0 in range(2):
        for i1 in range(6):
            s.status[b, i0, i1] = wp.uint8(0)
    for i0 in range(2):
        for i1 in range(6):
            s.status_ctr[b, i0, i1] = wp.uint8(0)
    for i0 in range(2):
        for i1 in range(6):
            s.sleep_skipped[b, i0, i1] = wp.uint8(0)
    for i0 in range(2):
        for i1 in range(6):
            s.slept_by_foe[b, i0, i1] = wp.uint8(0)
    for i0 in range(2):
        for i1 in range(6):
            s.species[b, i0, i1] = wp.uint16(0)
    for i0 in range(2):
        for i1 in range(6):
            s.level[b, i0, i1] = wp.uint8(0)
    for i0 in range(2):
        for i1 in range(6):
            s.gender[b, i0, i1] = wp.uint8(0)
    for i0 in range(2):
        for i1 in range(6):
            s.ability[b, i0, i1] = wp.uint8(0)
    for i0 in range(2):
        for i1 in range(6):
            s.item[b, i0, i1] = wp.uint8(0)
    for i0 in range(2):
        for i1 in range(6):
            s.hp_type[b, i0, i1] = wp.uint8(0)
    for i0 in range(2):
        for i1 in range(6):
            for i2 in range(5):
                s.stats[b, i0, i1, i2] = wp.uint16(0)
    for i0 in range(2):
        for i1 in range(6):
            s.maxhp[b, i0, i1] = wp.uint16(0)
    for i0 in range(2):
        for i1 in range(6):
            for i2 in range(4):
                s.moves[b, i0, i1, i2] = wp.uint8(0)
    for i0 in range(2):
        for i1 in range(6):
            for i2 in range(4):
                s.pp[b, i0, i1, i2] = wp.uint8(0)
    for i0 in range(2):
        for i1 in range(6):
            for i2 in range(4):
                s.max_pp[b, i0, i1, i2] = wp.uint8(0)
    for i0 in range(2):
        for i1 in range(6):
            s.party_pos[b, i0, i1] = wp.uint8(0)
    for i0 in range(2):
        for i1 in range(6):
            s.revealed[b, i0, i1] = wp.uint16(0)


@wp.func
def copy_battle(s: State, src: int, dst: int):
    s.weather[dst] = s.weather[src]
    s.weather_turns[dst] = s.weather_turns[src]
    s.turn[dst] = s.turn[src]
    s.result[dst] = s.result[src]
    s.last_used[dst] = s.last_used[src]
    s.rng_key[dst] = s.rng_key[src]
    s.rng_ctr[dst] = s.rng_ctr[src]
    s.rng_mode[dst] = s.rng_mode[src]
    s.err[dst] = s.err[src]
    s.phase[dst] = s.phase[src]
    s.turn_first[dst] = s.turn_first[src]
    for i0 in range(s.pending_act.shape[1]):
        s.pending_act[dst, i0] = s.pending_act[src, i0]
    for i0 in range(s.active.shape[1]):
        s.active[dst, i0] = s.active[src, i0]
    for i0 in range(s.request.shape[1]):
        s.request[dst, i0] = s.request[src, i0]
    for i0 in range(s.spikes.shape[1]):
        s.spikes[dst, i0] = s.spikes[src, i0]
    for i0 in range(s.wish_turns.shape[1]):
        s.wish_turns[dst, i0] = s.wish_turns[src, i0]
    for i0 in range(s.alive_mask.shape[1]):
        s.alive_mask[dst, i0] = s.alive_mask[src, i0]
    for i0 in range(s.knocked_mask.shape[1]):
        s.knocked_mask[dst, i0] = s.knocked_mask[src, i0]
    for i0 in range(s.truant_mask.shape[1]):
        s.truant_mask[dst, i0] = s.truant_mask[src, i0]
    for i0 in range(s.boosts.shape[1]):
        s.boosts[dst, i0] = s.boosts[src, i0]
    for i0 in range(s.vflags.shape[1]):
        s.vflags[dst, i0] = s.vflags[src, i0]
    for i0 in range(s.sub_hp.shape[1]):
        s.sub_hp[dst, i0] = s.sub_hp[src, i0]
    for i0 in range(s.confusion_turns.shape[1]):
        s.confusion_turns[dst, i0] = s.confusion_turns[src, i0]
    for i0 in range(s.encore_turns.shape[1]):
        s.encore_turns[dst, i0] = s.encore_turns[src, i0]
    for i0 in range(s.encore_move.shape[1]):
        s.encore_move[dst, i0] = s.encore_move[src, i0]
    for i0 in range(s.choice_move.shape[1]):
        s.choice_move[dst, i0] = s.choice_move[src, i0]
    for i0 in range(s.trap_turns.shape[1]):
        s.trap_turns[dst, i0] = s.trap_turns[src, i0]
    for i0 in range(s.trap_source.shape[1]):
        s.trap_source[dst, i0] = s.trap_source[src, i0]
    for i0 in range(s.perish_count.shape[1]):
        s.perish_count[dst, i0] = s.perish_count[src, i0]
    for i0 in range(s.yawn_turns.shape[1]):
        s.yawn_turns[dst, i0] = s.yawn_turns[src, i0]
    for i0 in range(s.stall_ctr.shape[1]):
        s.stall_ctr[dst, i0] = s.stall_ctr[src, i0]
    for i0 in range(s.twoturn_move.shape[1]):
        s.twoturn_move[dst, i0] = s.twoturn_move[src, i0]
    for i0 in range(s.last_move.shape[1]):
        s.last_move[dst, i0] = s.last_move[src, i0]
    for i0 in range(s.dmg_taken.shape[1]):
        s.dmg_taken[dst, i0] = s.dmg_taken[src, i0]
    for i0 in range(s.dmg_cat.shape[1]):
        s.dmg_cat[dst, i0] = s.dmg_cat[src, i0]
    for i0 in range(s.types.shape[1]):
        for i1 in range(s.types.shape[2]):
            s.types[dst, i0, i1] = s.types[src, i0, i1]
    for i0 in range(s.turn_flags.shape[1]):
        s.turn_flags[dst, i0] = s.turn_flags[src, i0]
    for i0 in range(s.moved_at.shape[1]):
        s.moved_at[dst, i0] = s.moved_at[src, i0]
    for i0 in range(s.moved_prio.shape[1]):
        s.moved_prio[dst, i0] = s.moved_prio[src, i0]
    for i0 in range(s.xf_stats.shape[1]):
        for i1 in range(s.xf_stats.shape[2]):
            s.xf_stats[dst, i0, i1] = s.xf_stats[src, i0, i1]
    for i0 in range(s.xf_moves.shape[1]):
        for i1 in range(s.xf_moves.shape[2]):
            s.xf_moves[dst, i0, i1] = s.xf_moves[src, i0, i1]
    for i0 in range(s.xf_pp.shape[1]):
        for i1 in range(s.xf_pp.shape[2]):
            s.xf_pp[dst, i0, i1] = s.xf_pp[src, i0, i1]
    for i0 in range(s.xf_max_pp.shape[1]):
        for i1 in range(s.xf_max_pp.shape[2]):
            s.xf_max_pp[dst, i0, i1] = s.xf_max_pp[src, i0, i1]
    for i0 in range(s.xf_ability.shape[1]):
        s.xf_ability[dst, i0] = s.xf_ability[src, i0]
    for i0 in range(s.xf_species.shape[1]):
        s.xf_species[dst, i0] = s.xf_species[src, i0]
    for i0 in range(s.xf_hp_type.shape[1]):
        s.xf_hp_type[dst, i0] = s.xf_hp_type[src, i0]
    for i0 in range(s.base_ability.shape[1]):
        s.base_ability[dst, i0] = s.base_ability[src, i0]
    for i0 in range(s.cached_spe.shape[1]):
        for i1 in range(s.cached_spe.shape[2]):
            s.cached_spe[dst, i0, i1] = s.cached_spe[src, i0, i1]
    for i0 in range(s.hp.shape[1]):
        for i1 in range(s.hp.shape[2]):
            s.hp[dst, i0, i1] = s.hp[src, i0, i1]
    for i0 in range(s.status.shape[1]):
        for i1 in range(s.status.shape[2]):
            s.status[dst, i0, i1] = s.status[src, i0, i1]
    for i0 in range(s.status_ctr.shape[1]):
        for i1 in range(s.status_ctr.shape[2]):
            s.status_ctr[dst, i0, i1] = s.status_ctr[src, i0, i1]
    for i0 in range(s.sleep_skipped.shape[1]):
        for i1 in range(s.sleep_skipped.shape[2]):
            s.sleep_skipped[dst, i0, i1] = s.sleep_skipped[src, i0, i1]
    for i0 in range(s.slept_by_foe.shape[1]):
        for i1 in range(s.slept_by_foe.shape[2]):
            s.slept_by_foe[dst, i0, i1] = s.slept_by_foe[src, i0, i1]
    for i0 in range(s.species.shape[1]):
        for i1 in range(s.species.shape[2]):
            s.species[dst, i0, i1] = s.species[src, i0, i1]
    for i0 in range(s.level.shape[1]):
        for i1 in range(s.level.shape[2]):
            s.level[dst, i0, i1] = s.level[src, i0, i1]
    for i0 in range(s.gender.shape[1]):
        for i1 in range(s.gender.shape[2]):
            s.gender[dst, i0, i1] = s.gender[src, i0, i1]
    for i0 in range(s.ability.shape[1]):
        for i1 in range(s.ability.shape[2]):
            s.ability[dst, i0, i1] = s.ability[src, i0, i1]
    for i0 in range(s.item.shape[1]):
        for i1 in range(s.item.shape[2]):
            s.item[dst, i0, i1] = s.item[src, i0, i1]
    for i0 in range(s.hp_type.shape[1]):
        for i1 in range(s.hp_type.shape[2]):
            s.hp_type[dst, i0, i1] = s.hp_type[src, i0, i1]
    for i0 in range(s.stats.shape[1]):
        for i1 in range(s.stats.shape[2]):
            for i2 in range(s.stats.shape[3]):
                s.stats[dst, i0, i1, i2] = s.stats[src, i0, i1, i2]
    for i0 in range(s.maxhp.shape[1]):
        for i1 in range(s.maxhp.shape[2]):
            s.maxhp[dst, i0, i1] = s.maxhp[src, i0, i1]
    for i0 in range(s.moves.shape[1]):
        for i1 in range(s.moves.shape[2]):
            for i2 in range(s.moves.shape[3]):
                s.moves[dst, i0, i1, i2] = s.moves[src, i0, i1, i2]
    for i0 in range(s.pp.shape[1]):
        for i1 in range(s.pp.shape[2]):
            for i2 in range(s.pp.shape[3]):
                s.pp[dst, i0, i1, i2] = s.pp[src, i0, i1, i2]
    for i0 in range(s.max_pp.shape[1]):
        for i1 in range(s.max_pp.shape[2]):
            for i2 in range(s.max_pp.shape[3]):
                s.max_pp[dst, i0, i1, i2] = s.max_pp[src, i0, i1, i2]
    for i0 in range(s.party_pos.shape[1]):
        for i1 in range(s.party_pos.shape[2]):
            s.party_pos[dst, i0, i1] = s.party_pos[src, i0, i1]
    for i0 in range(s.revealed.shape[1]):
        for i1 in range(s.revealed.shape[2]):
            s.revealed[dst, i0, i1] = s.revealed[src, i0, i1]


@wp.func
def copy_mon(s: State, src: int, side: int, slot: int, dst: int, dst_slot: int):
    s.cached_spe[dst, side, dst_slot] = s.cached_spe[src, side, slot]
    s.hp[dst, side, dst_slot] = s.hp[src, side, slot]
    s.status[dst, side, dst_slot] = s.status[src, side, slot]
    s.status_ctr[dst, side, dst_slot] = s.status_ctr[src, side, slot]
    s.sleep_skipped[dst, side, dst_slot] = s.sleep_skipped[src, side, slot]
    s.slept_by_foe[dst, side, dst_slot] = s.slept_by_foe[src, side, slot]
    s.species[dst, side, dst_slot] = s.species[src, side, slot]
    s.level[dst, side, dst_slot] = s.level[src, side, slot]
    s.gender[dst, side, dst_slot] = s.gender[src, side, slot]
    s.ability[dst, side, dst_slot] = s.ability[src, side, slot]
    s.item[dst, side, dst_slot] = s.item[src, side, slot]
    s.hp_type[dst, side, dst_slot] = s.hp_type[src, side, slot]
    for i in range(s.stats.shape[3]):
        s.stats[dst, side, dst_slot, i] = s.stats[src, side, slot, i]
    s.maxhp[dst, side, dst_slot] = s.maxhp[src, side, slot]
    for i in range(s.moves.shape[3]):
        s.moves[dst, side, dst_slot, i] = s.moves[src, side, slot, i]
    for i in range(s.pp.shape[3]):
        s.pp[dst, side, dst_slot, i] = s.pp[src, side, slot, i]
    for i in range(s.max_pp.shape[3]):
        s.max_pp[dst, side, dst_slot, i] = s.max_pp[src, side, slot, i]
    s.party_pos[dst, side, dst_slot] = s.party_pos[src, side, slot]
    s.revealed[dst, side, dst_slot] = s.revealed[src, side, slot]
